# Ko build configuration for infrastructure management system
# Note: Use environment variables for runtime config:
# - KO_DOCKER_REPO: Docker registry (e.g., registry.fly.io/your-app)
# - ENVIRONMENT: production|development

# Secure minimal base image for production
defaultBaseImage: alpine:latest

# Base image overrides for debug builds in development
baseImageOverrides:
  github.com/joeblew99/infra: alpine:latest

# Multi-platform builds (override with KO_DEFAULTPLATFORMS env var)
defaultPlatforms:
- linux/amd64
- linux/arm64

# Build configuration for optimized binaries
builds:
- id: infra-app
  main: ./
  env:
  - CGO_ENABLED=0
  - GOOS=linux
  flags:
  - -trimpath
  - -buildvcs=false
  ldflags:
  - -s -w
  - -X github.com/joeblew999/infra/pkg/cmd.GitHash={{.Env.GIT_HASH}}
  - -X github.com/joeblew999/infra/pkg/cmd.BuildTime={{.Date}}
  - -extldflags=-static

# Security and optimization settings
defaultEnv:
- CGO_ENABLED=0
- GOOS=linux