# Template for rendering fly.toml via core-tool config init.
# Variables:
#   AppName         - Fly application slug
#   PrimaryRegion   - default deployment region
#   KillSignal      - POSIX signal used during shutdown
#   KillTimeout     - duration before forced stop
#   Environment     - ordered environment variables (slice of key/value pairs)
#   Volume          - data volume mount (Source, Destination)
#   InternalPort    - port exposed by the container
#   Processes       - process group names associated with services
#   HTTPChecksPath  - path used for HTTP health checks
#   MetricsPort     - port exposing Prometheus metrics
#   MetricsPath     - path for metrics scraping
#   OrgSlug         - Fly organization slug (documented for reference)

app = 'test-core-app'
primary_region = 'syd'
kill_signal = 'SIGINT'
kill_timeout = '5s'

# Deploy within the personal organization by default.

[experimental]
  auto_rollback = true

[build]

[env]
  ENVIRONMENT = 'production'
  PORT = '1337'

[[mounts]]
  source = 'core_data'
  destination = '/app/.data'

[[services]]
  protocol = 'tcp'
  internal_port = 1337
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/status'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
