# Fly.io configuration for Infrastructure Management System
app = 'infra-mgmt'
primary_region = 'syd'  # Sydney - change to your preferred region
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

# Environment variables
[env]
  ENVIRONMENT = "production"
  PORT = "1337"

# Build configuration - using ko for container builds
[build]

# HTTP service configuration
[[services]]
  protocol = 'tcp'
  internal_port = 1337
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
    restart_limit = 0

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    restart_limit = 0
    method = 'get'
    path = '/status'
    protocol = 'http'
    tls_skip_verify = false

# Volume for persistent data
[[mounts]]
  source = 'infra_data'
  destination = '/app/.data'

# Machine configuration
[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'

# Metrics configuration
[metrics]
  port = 9091
  path = "/metrics"