# https://taskfile.dev

# https://taskfile.dev/reference/cli

# Runs Incus on a macOS host using Macpine.

# Its as idempotent as possible, so you can run it multiple times without issues and at any stage and it will be smart 
# about only running what is needed.


version: '3'

includes:
  task:
    taskfile: ./taskfiles/task_taskfile.yml
  git:
    taskfile: ./taskfiles/git_taskfile.yml
  claude:
    taskfile: ./taskfiles/claude_taskfile.yml
  
vars:
  

tasks:
  default:
    desc: List operations and state.
    cmds:
      - echo
      - echo "Runs Incus on a macOS host using Macpine."
      - echo
      - task --list-all
      - echo
    silent: true

  this:serve:
    desc: Run the project (usage - task this:dev [-- <args>])
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify
      - go fmt ./...
      - go run . {{.CLI_ARGS}}

  this:cli:
    desc: Run the project in CLI mode (usage - task this:cli [-- <args>])
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify
      - go fmt ./...
      - go run . --mode cli {{.CLI_ARGS}}

  this:test:all:
    desc: Run all Go tests in the project.
    cmds:
      - go test ./...

  this:claude:setup:
    desc: Setup claude MCP with our MPC.
    cmds:
      - task claude:mcp:remove
      - task claude:mcp:add
      - task claude:mcp:list

  this:claude:start:
    desc: Start the claude MCP server.
    cmds:
      - task claude:mcp:start
      # NOPW you can open Claude client
      

  this:git:push:
    desc: Push the repo branch to the remote
    cmds:
      - echo "Pushing the current branch to the remote repository..."
      - task git:add
      - task git:commit:all MSG="default"
      - task git:push

# NOTE:
# task this:git:tag TAG=v1.0.0 for a lightweight tag.
# task this:git:tag TAG=v1.0.0 MSG="Initial release" for an annotated tag.

  this:git:tag:
    desc: Tag and push the current branch to the remote (usage - task this:git:tag TAG=v1.0.0 [MSG="Release v1.0.0"])
    vars:
      TAG:
        sh: echo "{{.TAG}}"
        required: true
      MSG: '{{.MSG | default ""}}'
    cmds:
      - echo "Tagging and pushing..."
      - task git:tag TAG={{.TAG}} MSG="{{.MSG}}"
      - task git:tags:push


  this:git:tags:delete:single:
    desc: Delete a single tag both locally and remotely (usage - task this:git:tags:delete:single TAG=v1.0.0 [REMOTE=origin])
    vars:
      TAG:
        sh: echo "{{.TAG}}"
        required: true
      REMOTE: '{{.REMOTE | default ""}}'
    cmds:
      - task git:tags:delete:one TAG={{.TAG}} REMOTE={{.REMOTE}}

  

  


  

      
