# https://taskfile.dev

# https://taskfile.dev/reference/cli

# Runs Incus on a macOS host using Macpine.

# Its as idempotent as possible, so you can run it multiple times without issues and at any stage and it will be smart 
# about only running what is needed.


version: '3'

includes:
  git:
    taskfile: ./taskfiles/git_taskfile.yml
  

vars:
  

tasks:
  default:
    desc: List operations and state.
    cmds:
      - echo
      - echo "Runs Incus on a macOS host using Macpine."
      - echo
      - task --list-all
      - echo
    silent: true

  this:git:push:all:
    desc: Push the repo branch to the remote
    cmds:
      - echo "Pushing the current branch to the remote repository..."
      - task git:add
      - task git:commit-all MSG="default"
      - task git:push

  


  

      
