// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package types

type ComputeRequest struct {
	Operation string  `json:"operation"` // add, multiply, power
	A         float64 `json:"a"`
	B         float64 `json:"b"`
}

type ComputeResponse struct {
	Result    float64 `json:"result"`
	Operation string  `json:"operation"`
	Input     string  `json:"input"`
}

type EchoRequest struct {
	Message string `json:"message"`
}

type EchoResponse struct {
	Echo      string `json:"echo"`
	Timestamp string `json:"timestamp"`
	Length    int    `json:"length"`
}

type PingResponse struct {
	Message   string `json:"message"`
	Timestamp string `json:"timestamp"`
	Server    string `json:"server"`
}

type StatusResponse struct {
	Status  string            `json:"status"`
	Version string            `json:"version"`
	Uptime  string            `json:"uptime"`
	Metrics map[string]string `json:"metrics"`
}
