// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	"github.com/joeblew999/infra/api/deck/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/deck/download/:id",
				Handler: DownloadDeckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/deck/generate",
				Handler: GenerateDeckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/deck/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/deck/list",
				Handler: ListDecksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/deck/status/:id",
				Handler: GetDeckStatusHandler(serverCtx),
			},
		},
	)
}
