processes:
    caddy:
        availability:
            restart: always
        command: .dep/caddy
        depends_on:
            pocketbase:
                condition: process_healthy
        environment:
            - CADDY_HOST=0.0.0.0
        log:
            max_files: 5
            timestamps: true
        working_dir: .
    nats:
        availability:
            restart: always
        command: .dep/nats
        environment:
            - NATS_DATA_DIR=.data/nats
        log:
            max_files: 10
            max_size: 20mb
        readiness_probe:
            failure_threshold: 5
            http_get:
                url: http://127.0.0.1:8222/healthz
            initial_delay_seconds: 10
            period_seconds: 5
            success_threshold: 1
            timeout_seconds: 3
        working_dir: .
    pocketbase:
        availability:
            restart: always
        command: .dep/pocketbase
        depends_on:
            nats:
                condition: process_healthy
        environment:
            - POCKETBASE_DIR=.data/pocketbase
        readiness_probe:
            failure_threshold: 5
            http_get:
                url: http://127.0.0.1:8090/api/health
            initial_delay_seconds: 5
            period_seconds: 5
            success_threshold: 1
            timeout_seconds: 3
        working_dir: .
version: "0.5"
