processes:
    caddy:
        availability:
            restart: always
        command: .dep/caddy
        depends_on:
            pocketbase:
                condition: process_healthy
        environment:
            - CADDY_HOST=0.0.0.0
        log:
            max_files: 5
            timestamps: true
        working_dir: .
    nats:
        availability:
            restart: always
        command: .dep/nats
        environment:
            - NATS_DATA_DIR=.data/nats
            - PILLOW_AUTO_SCALE=true
            - PILLOW_BACKEND=pillow
            - PILLOW_JETSTREAM=true
            - PILLOW_TOPOLOGY=hub-spoke
        log:
            max_files: 10
            max_size: 20mb
        readiness_probe:
            failure_threshold: 5
            http_get:
                url: http://127.0.0.1:8222/healthz
            initial_delay_seconds: 10
            period_seconds: 5
            success_threshold: 1
            timeout_seconds: 3
        working_dir: .
    pocketbase:
        availability:
            restart: always
        command: .dep/pocketbase
        depends_on:
            nats:
                condition: process_healthy
        environment:
            - CORE_POCKETBASE_ADMIN_EMAIL=admin@localhost
            - CORE_POCKETBASE_ADMIN_PASSWORD=changeme123
            - CORE_POCKETBASE_APPLE_CLIENT_ID=
            - CORE_POCKETBASE_APPLE_CLIENT_SECRET=
            - CORE_POCKETBASE_APP_URL=http://localhost:8090
            - CORE_POCKETBASE_GITHUB_CLIENT_ID=
            - CORE_POCKETBASE_GITHUB_CLIENT_SECRET=
            - CORE_POCKETBASE_GOOGLE_CLIENT_ID=
            - CORE_POCKETBASE_GOOGLE_CLIENT_SECRET=
            - CORE_POCKETBASE_MICROSOFT_CLIENT_ID=
            - CORE_POCKETBASE_MICROSOFT_CLIENT_SECRET=
            - CORE_POCKETBASE_SMTP_FROM=
            - CORE_POCKETBASE_SMTP_HOST=
            - CORE_POCKETBASE_SMTP_PASSWORD=
            - CORE_POCKETBASE_SMTP_PORT=
            - CORE_POCKETBASE_SMTP_TLS=
            - CORE_POCKETBASE_SMTP_USERNAME=
            - POCKETBASE_DIR=.data/pocketbase
        readiness_probe:
            failure_threshold: 5
            http_get:
                url: http://127.0.0.1:8090/api/health
            initial_delay_seconds: 5
            period_seconds: 5
            success_threshold: 1
            timeout_seconds: 3
        working_dir: .
version: "0.5"
