// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	"github.com/joeblew999/infra/api/fast/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/compute",
				Handler: ComputeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/echo",
				Handler: EchoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/status",
				Handler: StatusHandler(serverCtx),
			},
		},
	)
}
