# Template for rendering .ko.yaml via core-tool config init.
# Variables:
#   BaseImage   - base image used when ko builds binaries
#   Module      - module import path (for base image overrides)
#   ImportPath  - relative path to the Go main package
#   BuildID     - identifier for the ko build stanza
#   Platforms   - list of GOOS/GOARCH targets
#   BuildEnv    - environment variables applied within the build stanza
#   BuildFlags  - go build flags passed by ko
#   LDFlags     - linker flags applied during build
#   DefaultEnv  - environment variables applied globally
#   Repository  - default KO repository

defaultBaseImage: alpine:latest

baseImageOverrides:
  github.com/joeblew999/infra/core: alpine:latest

# KO publishes default to the ko.local/core registry.

defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: core-app
    main: ./cmd/core
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

  - id: nats
    main: ./cmd/nats
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

  - id: pocketbase
    main: ./cmd/pocketbase
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

  - id: pocketbase-ha
    main: ./cmd/pocketbase-ha
    env:
      - CGO_ENABLED=1
      - GOOS=linux
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

defaultEnv:
  - CGO_ENABLED=0
  - GOOS=linux
