// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	"github.com/joeblew999/infra/api/testservice/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mcp",
				Handler: McpHandler(serverCtx),
			},
		},
	)
}
