// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package types

type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Ready   bool   `json:"ready"`
}

type McpRequest struct {
	Jsonrpc string `json:"jsonrpc"`
	Method  string `json:"method"`
	Id      int64  `json:"id"`
	Params  string `json:"params,optional"`
}

type McpResponse struct {
	Jsonrpc string `json:"jsonrpc"`
	Id      int64  `json:"id"`
	Result  string `json:"result,optional"`
	Error   string `json:"error,optional"`
}
