// Code generated by go generate; DO NOT EDIT.
// This file was generated by pkg/config/generate_binaries.go from pkg/dep/dep.json

package config

// Generated at 2025-10-15 15:29:18.876907 +0700 +07 m=+0.001559792

// Binary name constants - auto-generated from dep.json
// Using constants prevents garble obfuscation and provides type safety
const (
	BinaryFlyctl = "flyctl" // CLI for managing Fly.io applications and infrastructure
	BinaryKo = "ko" // Build and deploy Go applications to Kubernetes with minimal configuration
	BinaryCaddy = "caddy" // Powerful, enterprise-ready web server with automatic HTTPS
	BinaryTask = "task" // Task runner and build tool that uses YAML configuration
	BinaryTofu = "tofu" // Open-source Terraform fork for infrastructure as code
	BinaryBento = "bento" // High-performance stream processor for data pipelines
	BinaryGarble = "garble" // Go build obfuscation tool for creating tamper-resistant binaries
	BinaryBun = "bun" // Fast JavaScript runtime, package manager, and bundler
	BinaryClaude = "claude" // Claude Code CLI for AI-powered development assistance
	BinaryNats = "nats" // CLI for NATS messaging system and JetStream management
	BinaryNsc = "nsc" // NATS account and credentials management CLI
	BinaryNatsServer = "nats-server" // NATS Server is a simple, high performance open source messaging system.
	BinaryNatsTop = "nats-top" // A top-like tool for monitoring NATS servers.
	BinaryLitestream = "litestream" // SQLite replication and disaster recovery tool
	BinaryToki = "toki" // Multi-language translation tool with pluralization support
	BinaryGoose = "goose" // AI-powered software development agent for complex tasks
	BinaryGs = "gs" // Manage stacked Git branches for systematic development workflows
	BinaryCrush = "crush" // SSH client with advanced features and modern interface
	BinaryGh = "gh" // GitHub CLI for managing repositories, releases, and GitHub operations
	BinaryTinygo = "tinygo" // Go compiler for microcontrollers and WebAssembly
	BinaryXtemplate = "xtemplate" // HTML/template-based hypertext preprocessor and rapid web development server
	BinaryGoctl = "goctl" // Code generation tool for go-zero microservices framework
	BinaryNatsS3 = "nats-s3" // S3 gateway for NATS JetStream Object Store
	BinaryMox = "mox" // Modern secure mail server with automatic HTTPS, DMARC, and webmail
	BinaryPocketbase = "pocketbase" // Realtime backend and admin dashboard for your apps
	BinaryUtm = "utm" // Full-featured system emulator and virtual machine host for macOS
	BinaryHugo = "hugo" // Fast and flexible static site generator with modern theming support
)

// AllBinaryNames returns all available binary names from dep.json
func AllBinaryNames() []string {
	return []string{
		BinaryFlyctl,
		BinaryKo,
		BinaryCaddy,
		BinaryTask,
		BinaryTofu,
		BinaryBento,
		BinaryGarble,
		BinaryBun,
		BinaryClaude,
		BinaryNats,
		BinaryNsc,
		BinaryNatsServer,
		BinaryNatsTop,
		BinaryLitestream,
		BinaryToki,
		BinaryGoose,
		BinaryGs,
		BinaryCrush,
		BinaryGh,
		BinaryTinygo,
		BinaryXtemplate,
		BinaryGoctl,
		BinaryNatsS3,
		BinaryMox,
		BinaryPocketbase,
		BinaryUtm,
		BinaryHugo,
	}
}

// IsBinaryNameValid checks if a binary name is valid according to dep.json
func IsBinaryNameValid(name string) bool {
	for _, validName := range AllBinaryNames() {
		if validName == name {
			return true
		}
	}
	return false
}
