name: Simple CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME || 'infra-mgmt' }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # For api-check comparisons
    
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    # Run the same commands you use locally
    - name: CI Checks
      run: go run . ci
    
    - name: API Compatibility Check
      if: github.event_name == 'pull_request'
      run: go run . api-check --old origin/${{ github.base_ref }} --new HEAD
    
    - name: Build Test
      run: go run . build --push=false
    
    # Deploy only on main branch pushes
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ -z "$FLY_API_TOKEN" ]; then
          echo "❌ FLY_API_TOKEN not set - skipping deploy"
          exit 0
        fi
        go run . deploy --app ${{ env.FLY_APP_NAME }} --env production