name: Simple CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: ${{ secrets.FLY_APP_NAME || 'infra-mgmt' }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # For api-check comparisons
    
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    # Run the same commands you'd run locally
    - name: Tests
      run: go test ./...
    
    # Deploy handles everything: build + deploy in one mega workflow
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ -z "$FLY_API_TOKEN" ]; then
          echo "❌ FLY_API_TOKEN not set - skipping deploy"
          exit 0
        fi
        go run . deploy --env production